/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Admin;

import LogIn.LoginForm;
import config.config;
import java.awt.GridLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Administrator
 */
public class vehicles extends javax.swing.JFrame {

    /**
     * Creates new form vehicles
     */
    public vehicles() {
        initComponents();
        ensureVehiclesTable();
        loadVehiclesIntoTable();
        initListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Vehicle Registration ");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Add Vehicle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Update Vehicle");

        jButton3.setText("Delete Vehicle");

        jButton4.setText("View Vehicle");

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setText("Refresh");

        jButton6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton6.setText("Back to Dashboard");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(178, 178, 178)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(26, 26, 26)
                            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton5)
                        .addComponent(jButton6)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Wire button actions for the admin vehicles table view.
     */
    private void initListeners() {
        // "Add Vehicle" → open dialog and insert a new vehicle
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleAddVehicle();
            }
        });

        // "Update Vehicle" → edit the selected vehicle
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleUpdateVehicle();
            }
        });

        // "Delete Vehicle" → delete the selected vehicle
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleDeleteVehicle();
            }
        });

        // "View Vehicle" → show details of the selected vehicle
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleViewVehicle();
            }
        });

        // "Refresh" → reload vehicles data into the table
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadVehiclesIntoTable();
            }
        });

        // "Back to Dashboard" → return to the admin dashboard
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new adminDashboard().setVisible(true);
                dispose();
            }
        });
    }

    /**
     * Ensure the vehicles table exists in the database.
     */
    private void ensureVehiclesTable() {
        try (Connection conn = config.connectDB();
             Statement stmt = conn != null ? conn.createStatement() : null) {

            if (stmt == null) {
                return;
            }

            stmt.executeUpdate(
                    "CREATE TABLE IF NOT EXISTS vehicles ("
                    + "id INTEGER PRIMARY KEY AUTOINCREMENT, "
                    + "model TEXT NOT NULL, "
                    + "vin TEXT NOT NULL UNIQUE, "
                    + "owner_name TEXT NOT NULL, "
                    + "plate_number TEXT NOT NULL, "
                    + "reg_start_date TEXT NOT NULL, "
                    + "reg_end_date TEXT NOT NULL"
                    + ")"
            );
        } catch (SQLException e) {
            System.out.println("Error ensuring vehicles table: " + e.getMessage());
        }
    }

    /**
     * Load all vehicles from the database into the JTable.
     */
    private void loadVehiclesIntoTable() {
        String sql = "SELECT id, model, vin, owner_name, plate_number, reg_start_date, reg_end_date FROM vehicles";

        DefaultTableModel tableModel = new DefaultTableModel(
                new Object[]{"ID", "Model", "VIN", "Owner Name", "Plate Number", "Reg Start", "Reg End"},
                0
        );

        try (Connection conn = config.connectDB();
             PreparedStatement pstmt = conn != null ? conn.prepareStatement(sql) : null;
             ResultSet rs = (pstmt != null) ? pstmt.executeQuery() : null) {

            if (pstmt == null || rs == null) {
                JOptionPane.showMessageDialog(this,
                        "Unable to load vehicles from the database.",
                        "Connection Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            while (rs.next()) {
                Object[] row = new Object[]{
                    rs.getInt("id"),
                    rs.getString("model"),
                    rs.getString("vin"),
                    rs.getString("owner_name"),
                    rs.getString("plate_number"),
                    rs.getString("reg_start_date"),
                    rs.getString("reg_end_date")
                };
                tableModel.addRow(row);
            }

            jTable1.setModel(tableModel);
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error loading vehicles: " + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Handle adding a new vehicle via a dialog.
     */
    private void handleAddVehicle() {
        JTextField modelField = new JTextField();
        JTextField vinField = new JTextField();
        JTextField ownerField = new JTextField();
        JTextField plateField = new JTextField();
        JTextField regStartField = new JTextField();
        JTextField regEndField = new JTextField();

        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Model:"));
        panel.add(modelField);
        panel.add(new JLabel("VIN:"));
        panel.add(vinField);
        panel.add(new JLabel("Owner Name:"));
        panel.add(ownerField);
        panel.add(new JLabel("Plate Number:"));
        panel.add(plateField);
        panel.add(new JLabel("Reg Start Date:"));
        panel.add(regStartField);
        panel.add(new JLabel("Reg End Date:"));
        panel.add(regEndField);

        int result = JOptionPane.showConfirmDialog(
                this,
                panel,
                "Add Vehicle",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        String model = modelField.getText().trim();
        String vin = vinField.getText().trim();
        String ownerName = ownerField.getText().trim();
        String plateNumber = plateField.getText().trim();
        String regStart = regStartField.getText().trim();
        String regEnd = regEndField.getText().trim();

        if (model.isEmpty() || vin.isEmpty() || ownerName.isEmpty()
                || plateNumber.isEmpty() || regStart.isEmpty() || regEnd.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please fill in all fields.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "INSERT INTO vehicles(model, vin, owner_name, plate_number, reg_start_date, reg_end_date) "
                + "VALUES(?, ?, ?, ?, ?, ?)";

        try (Connection conn = config.connectDB();
             PreparedStatement pstmt = conn != null ? conn.prepareStatement(sql) : null) {

            if (pstmt == null) {
                JOptionPane.showMessageDialog(this,
                        "Unable to connect to the database.",
                        "Connection Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            pstmt.setString(1, model);
            pstmt.setString(2, vin);
            pstmt.setString(3, ownerName);
            pstmt.setString(4, plateNumber);
            pstmt.setString(5, regStart);
            pstmt.setString(6, regEnd);

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Vehicle added successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            loadVehiclesIntoTable();
        } catch (SQLException e) {
            if (e.getMessage() != null && e.getMessage().toLowerCase().contains("unique")) {
                JOptionPane.showMessageDialog(this,
                        "This VIN is already registered.",
                        "Duplicate VIN",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Error adding vehicle: " + e.getMessage(),
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * Handle updating the selected vehicle.
     */
    private void handleUpdateVehicle() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a vehicle to update.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        int id = (int) model.getValueAt(selectedRow, 0);
        String currentModel = model.getValueAt(selectedRow, 1).toString();
        String currentVin = model.getValueAt(selectedRow, 2).toString();
        String currentOwner = model.getValueAt(selectedRow, 3).toString();
        String currentPlate = model.getValueAt(selectedRow, 4).toString();
        String currentRegStart = model.getValueAt(selectedRow, 5).toString();
        String currentRegEnd = model.getValueAt(selectedRow, 6).toString();

        JTextField modelField = new JTextField(currentModel);
        JTextField vinField = new JTextField(currentVin);
        JTextField ownerField = new JTextField(currentOwner);
        JTextField plateField = new JTextField(currentPlate);
        JTextField regStartField = new JTextField(currentRegStart);
        JTextField regEndField = new JTextField(currentRegEnd);

        JPanel panel = new JPanel(new GridLayout(0, 2, 5, 5));
        panel.add(new JLabel("Model:"));
        panel.add(modelField);
        panel.add(new JLabel("VIN:"));
        panel.add(vinField);
        panel.add(new JLabel("Owner Name:"));
        panel.add(ownerField);
        panel.add(new JLabel("Plate Number:"));
        panel.add(plateField);
        panel.add(new JLabel("Reg Start Date:"));
        panel.add(regStartField);
        panel.add(new JLabel("Reg End Date:"));
        panel.add(regEndField);

        int result = JOptionPane.showConfirmDialog(
                this,
                panel,
                "Update Vehicle",
                JOptionPane.OK_CANCEL_OPTION,
                JOptionPane.PLAIN_MESSAGE
        );

        if (result != JOptionPane.OK_OPTION) {
            return;
        }

        String newModel = modelField.getText().trim();
        String newVin = vinField.getText().trim();
        String newOwner = ownerField.getText().trim();
        String newPlate = plateField.getText().trim();
        String newRegStart = regStartField.getText().trim();
        String newRegEnd = regEndField.getText().trim();

        if (newModel.isEmpty() || newVin.isEmpty() || newOwner.isEmpty()
                || newPlate.isEmpty() || newRegStart.isEmpty() || newRegEnd.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Please fill in all fields.",
                    "Validation Error",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        String sql = "UPDATE vehicles "
                + "SET model = ?, vin = ?, owner_name = ?, plate_number = ?, reg_start_date = ?, reg_end_date = ? "
                + "WHERE id = ?";

        try (Connection conn = config.connectDB();
             PreparedStatement pstmt = conn != null ? conn.prepareStatement(sql) : null) {

            if (pstmt == null) {
                JOptionPane.showMessageDialog(this,
                        "Unable to connect to the database.",
                        "Connection Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            pstmt.setString(1, newModel);
            pstmt.setString(2, newVin);
            pstmt.setString(3, newOwner);
            pstmt.setString(4, newPlate);
            pstmt.setString(5, newRegStart);
            pstmt.setString(6, newRegEnd);
            pstmt.setInt(7, id);

            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Vehicle updated successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            loadVehiclesIntoTable();
        } catch (SQLException e) {
            if (e.getMessage() != null && e.getMessage().toLowerCase().contains("unique")) {
                JOptionPane.showMessageDialog(this,
                        "This VIN is already registered to another vehicle.",
                        "Duplicate VIN",
                        JOptionPane.WARNING_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Error updating vehicle: " + e.getMessage(),
                        "Database Error",
                        JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    /**
     * Handle deleting the selected vehicle.
     */
    private void handleDeleteVehicle() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a vehicle to delete.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int id = (int) model.getValueAt(selectedRow, 0);
        String plate = model.getValueAt(selectedRow, 4).toString();

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Are you sure you want to delete vehicle with plate \"" + plate + "\"?",
                "Confirm Delete",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        String sql = "DELETE FROM vehicles WHERE id = ?";

        try (Connection conn = config.connectDB();
             PreparedStatement pstmt = conn != null ? conn.prepareStatement(sql) : null) {

            if (pstmt == null) {
                JOptionPane.showMessageDialog(this,
                        "Unable to connect to the database.",
                        "Connection Error",
                        JOptionPane.ERROR_MESSAGE);
                return;
            }

            pstmt.setInt(1, id);
            pstmt.executeUpdate();

            JOptionPane.showMessageDialog(this,
                    "Vehicle deleted successfully!",
                    "Success",
                    JOptionPane.INFORMATION_MESSAGE);

            loadVehiclesIntoTable();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error deleting vehicle: " + e.getMessage(),
                    "Database Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * Handle viewing details of the selected vehicle.
     */
    private void handleViewVehicle() {
        int selectedRow = jTable1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this,
                    "Please select a vehicle to view.",
                    "No Selection",
                    JOptionPane.WARNING_MESSAGE);
            return;
        }

        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();

        String details = "ID: " + model.getValueAt(selectedRow, 0)
                + "\nModel: " + model.getValueAt(selectedRow, 1)
                + "\nVIN: " + model.getValueAt(selectedRow, 2)
                + "\nOwner Name: " + model.getValueAt(selectedRow, 3)
                + "\nPlate Number: " + model.getValueAt(selectedRow, 4)
                + "\nReg Start Date: " + model.getValueAt(selectedRow, 5)
                + "\nReg End Date: " + model.getValueAt(selectedRow, 6);

        JOptionPane.showMessageDialog(this,
                details,
                "Vehicle Details",
                JOptionPane.INFORMATION_MESSAGE);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
